### PR TITLE
Allow adding a custom header, for instance for extend SoapHeader clas…

### PR DESCRIPTION
**Pull request by pradius-fut**
…ses (In our case for WsseAuth)

### CODE REVIEW

**Comment by artisaninweb** [comment]
There is already a function to add a custom header, why add another one?

**Comment by mro95** [comment]
Reading the code is not that hard

**Comment by pradius-fut** [comment]
Hi, if i missed it, i'm sorry, but, are you talking about:
```
  public function header($namespace, $name, $data = null, $mustUnderstand = false, $actor = null)
```

Because that one is not doing what i need in our use case.

**Comment by mro95** [comment]
Can you be more specific?
this is how i add headers
```````
$auth = [
    'Username' => 'foo',
    'Password' => 'bar'
];                                                                                                                                                                                                        

$this->name($this->name)->header('https://url/', 'AuthenticationHeader', $auth);

**Comment by pradius-fut** [comment]
Yes, that one i noticed.
But, in our case we needed to use a new header class that EXTENDS the normal SoapHeader class.
Like: 
```
class WsseAuthHeader extends \SoapHeader
```
And then i needed to be able to do something like:
```
 $service->name('ShippingStatus')
                    ->wsdl(self::APIURL)
                    ->addHeader(new WsseAuthHeader(self::APICUSTOMER, sha1($token)))
                    ->cache(WSDL_CACHE_NONE);
```

**Comment by artisaninweb** [comment]
Aah now i understand.
Rename the function to `customHeader` add it to the readme.md and i will merge it.

**Comment by artisaninweb** [comment]
Merged and released to version: 0.2.5.10

**Pull request merged**
