### PR TITLE
added magic function

### PR DESCRIPTION
**Pull request by iwex**
Added magic method which can accept not only arrays but objects too.

### CODE REVIEW

**Comment by artisaninweb** [comment]
I'm not a big fan of magic functions.
Can you give me a good reason to add this?

And why the change of:
```php
call_user_func_array()
```
To:
```php
call_user_func()
```

**Comment by iwex** [comment]
Some people want to use objects instead of arrays for exchanging using SOAP

**Comment by iwex** [comment]
Some people want to use stdObject instead of arrays in exchanging using SOAP

**Comment by artisaninweb** [comment]
Added the use for stdClass in commit bf6744f
Not a big fan of magic functions.

**Pull request closed without merging**
